export enum TableContent {
  authorName = "{\"attribute\":\"Author Name\",\"isOperator\":true,\"conditions\":[{\"condition\":\"Kokosza\",\"operator\":\"!=\"},{\"condition\":\"Kremis\",\"operator\":\"=\"},{\"condition\":\"Matecki\",\"operator\":\"=\"},{\"condition\":\"Lukasiewicz\",\"operator\":\"=\"}],\"addable\":true}",
  pdbID = "{\"attribute\":\"PDB ID\",\"isOperator\":false,\"conditions\":[{\"condition\":\"1234\",\"operator\":\"\"},{\"condition\":\"4321\",\"operator\":\"\"}],\"addable\":true}",
  keyword = "{\"attribute\":\"Keyword\",\"isOperator\":false,\"conditions\":[{\"condition\":\"Hooman\",\"operator\":\"\"}],\"addable\":true}",
  expMethod = "{\"attribute\":\"Experimental Method\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"X-Ray\",\"operator\":\"\"},{\"condition\":\"NMR\",\"operator\":\"\"}],\"addable\":false}",
  molType = "{\"attribute\":\"Molecule Type\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"DNA\",\"operator\":\"\"},{\"condition\":\"RNA\",\"operator\":\"\"},{\"condition\":\"other\",\"operator\":\"\"}],\"addable\":false}",
  typeNoStrands = "{\"attribute\":\"Type (by no. of strands)\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"unimolecular\",\"operator\":\"\"},{\"condition\":\"bimolecular\",\"operator\":\"\"},{\"condition\":\"tetramolecular\",\"operator\":\"\"}],\"addable\":false}",
  handedness = "{\"attribute\":\"Handedness\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"right\",\"operator\":\"\"},{\"condition\":\"left\",\"operator\":\"\"}],\"addable\":false}",
  noOfTetrads = "{\"attribute\":\"Number of tetrads\",\"isOperator\":true,\"conditions\":[{\"condition\":\"3\",\"operator\":\">\"},{\"condition\":\"2\",\"operator\":\"<\"},{\"condition\":\"10\",\"operator\":\">=\"}],\"addable\":true}",
  ions = "{\"attribute\":\"Ions\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"Na\",\"operator\":\"\"},{\"condition\":\"K\",\"operator\":\"\"},{\"condition\":\"Pt\",\"operator\":\"\"},{\"condition\":\"Tl\",\"operator\":\"\"}],\"addable\":false}",
  webbaDaSilva = "{ \"attribute\": \"Webba da Silva\", \"isOperator\": false, \"conditions\": [{ \"condition\": \"any\", \"operator\": \"\" }, { \"condition\": \"web topology\", \"operator\": \"\" }, { \"condition\": \"tetrad comination\", \"operator\": \"\" }], \"addable\": false }",
  onzClass = "{\"attribute\":\"ONZ class\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"N-\",\"operator\":\"\"},{\"condition\":\"Z-\",\"operator\":\"\"},{\"condition\":\"O-\",\"operator\":\"\"}],\"addable\":false}",
  pdbDeposition = "{\"attribute\":\"PDB Deposition\",\"isOperator\":true,\"conditions\":[{\"condition\":\"2010-03-21\",\"operator\":\"<\"},{\"condition\":\"2001-01-01\",\"operator\":\">=\"}],\"addable\":true}",
  gtractSeq = "{\"attribute\":\"G-tract sequence\",\"isOperator\":false,\"conditions\":[{\"condition\":\"GGGG\",\"operator\":\"\"},{\"condition\":\"G\",\"operator\":\"\"}],\"addable\":true}",
  bulges = "{\"attribute\":\"Bulges\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"with bulges\",\"operator\":\"\"},{\"condition\":\"without bulges\",\"operator\":\"\"}],\"addable\":false}",
  vLoops = "{\"attribute\":\"V-Loops\",\"isOperator\":false,\"conditions\":[{\"condition\":\"any\",\"operator\":\"\"},{\"condition\":\"with V-Loops\",\"operator\":\"\"},{\"condition\":\"without V-Loops\",\"operator\":\"\"}],\"addable\":false}",
  sequence = "{\"attribute\":\"Sequence\",\"isOperator\":true,\"conditions\":[{\"condition\":\"GCGGGGGGGGG\",\"operator\":\"includes\"},{\"condition\":\"G\",\"operator\":\"3'->5'\"}],\"addable\":true}"
}
